#:include "common.fypp"
#:set RANKS = range(1, 2+1)
#:set R_KINDS_TYPES = list(zip(REAL_KINDS, REAL_TYPES, REAL_SUFFIX))
#:set C_KINDS_TYPES = list(zip(CMPLX_KINDS, CMPLX_TYPES, CMPLX_SUFFIX))
#:set KINDS_TYPES = R_KINDS_TYPES+C_KINDS_TYPES
#! define ranks without parentheses
#:def rksfx2(rank)
#{if rank > 0}#${":," + ":," * (rank - 1)}$#{endif}#
#:enddef
submodule (stdlib_sparse_sptrv) stdlib_sparse_sptrv_csr
contains

    !! sptrv_csr
    #:for k1, t1, s1 in (KINDS_TYPES)
    #:for rank in RANKS
    module subroutine sptrv_csr_${rank}$d_${s1}$(matrix,vec_x,vec_y,op)
        type(CSR_${s1}$_type), intent(in) :: matrix
        ${t1}$, intent(in)    :: vec_x${ranksuffix(rank)}$
        ${t1}$, intent(inout) :: vec_y${ranksuffix(rank)}$
        character(1), intent(in), optional :: op
        character(1) :: op_
        integer(ilp) :: i, j

        op_ = sparse_op_none; if (present(op)) op_ = op
        vec_y = vec_x

        associate( data => matrix%data, col => matrix%col, rowptr => matrix%rowptr, &
            & nrows => matrix%nrows, storage => matrix%storage )

            if ( storage == sparse_upper .and. op_ == sparse_op_none ) then
                ! Solve U*y = x; backward substitution
                do i = nrows, 1, -1
                    do j = rowptr(i)+1, rowptr(i+1)-1
                        vec_y(${rksfx2(rank-1)}$i) = vec_y(${rksfx2(rank-1)}$i) - data(j) * vec_y(${rksfx2(rank-1)}$col(j))
                    end do
                    vec_y(${rksfx2(rank-1)}$i) = vec_y(${rksfx2(rank-1)}$i) / data(rowptr(i))
                end do

            else if ( storage == sparse_upper .and. op_ == sparse_op_transpose ) then
                ! Solve U^T*y = x; forward substitution
                do i = 1, nrows
                    vec_y(${rksfx2(rank-1)}$i) = vec_y(${rksfx2(rank-1)}$i) / data(rowptr(i))
                    do j = rowptr(i)+1, rowptr(i+1)-1
                        vec_y(${rksfx2(rank-1)}$col(j)) = vec_y(${rksfx2(rank-1)}$col(j)) - data(j) * vec_y(${rksfx2(rank-1)}$i)
                    end do
                end do
            end if
        end associate
    end subroutine

    #:endfor
    #:endfor

end submodule stdlib_sparse_sptrv_csr
