name: Generate tarball

on: [push, pull_request]

env:
  SRCDIR: src

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v1 # Use pip to install latest CMake, & FORD/Jin2For, etc.
      with:
        python-version: 3.x

    - name: Install fypp
      run: pip install --upgrade fypp

    - name: Generate f90 files
      run: |
          find src -name "*.fypp" -print | cut -f1 -d . | xargs -i{} fypp {}.fypp {}.f90 #Generate pre-proceessed files
          rsync -av --exclude "*.fypp" . stdlib/
          zip -r stdlib.zip stdlib

    - name: Upload tarball
      uses: actions/upload-artifact@v2
      with:
        name: stdlib.zip
        path: ./stdlib.zip
